import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tarasiuk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Tarasiuk.dev
        </h1>

        <p className={styles.description}>
          Select the Tarasiuk below{' '}
        </p>

        <div className={styles.grid}>
          <a href="https://tarasiuk.dev/alex" className={styles.card}>
            <h2> Alex &rarr;</h2>
            <p>Master Generalist. Relentless Investigator.</p>
          </a>

          <a href="https://tarasiuk.dev/joel" className={styles.card}>
            <h2>Joel &rarr;</h2>
            <p>Multi-cultural designer with a flair for User Interfaces</p>
          </a>

          <a
            href="https://tarasiuk.dev/nathan"
            className={styles.card}
          >
            <h2>Nathan &rarr;</h2>
            <p>The self-taught fullstack wiz-kid.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
